name: OneDrive Sync

on: workflow_dispatch

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rclone
      run: sudo curl https://rclone.org/install.sh | sudo bash

    - name: Configure Rclone
      env:
        RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
      run: |
        mkdir -p ~/.config/rclone
        echo "$RCLONE_CONFIG" > ~/.config/rclone/rclone.conf
        echo "=== 配置文件内容 ==="
        cat ~/.config/rclone/rclone.conf

    - name: Validate Config
      run: rclone config show onedrive

    - name: Sync Files
      run: |
        mkdir -p ./LightNovel
        rclone sync onedrive:/LightNovel ./LightNovel -v --log-level DEBUG

    - name: Commit changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "Sync Bot"
        git config --global user.email "sync@bot"
        git add .
        git diff-index --quiet HEAD || git commit -m "Auto Sync"
        git push
