name: OneDrive Sync

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Rclone
      run: sudo curl https://rclone.org/install.sh | sudo bash

    - name: Configure Rclone
      env:
        RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      run: |
        mkdir -p ~/.config/rclone
        echo "$RCLONE_CONFIG" > ~/.config/rclone/rclone.conf
        sed -i "s/your_client_id_here/$CLIENT_ID/g" ~/.config/rclone/rclone.conf
        sed -i "s/your_client_secret_here/$CLIENT_SECRET/g" ~/.config/rclone/rclone.conf
        cat ~/.config/rclone/rclone.conf

    - name: Validate Connection
      run: rclone lsd onedrive:

    - name: Prepare Directory
      run: mkdir -p ./LightNovel

    - name: Sync from OneDrive
      run: rclone sync onedrive:/LightNovel ./LightNovel -v

    - name: Commit changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git config --global --add safe.directory /github/workspace
        git add .
        git commit -m "[Auto] Sync $(date +'%Y-%m-%d')" || echo "No changes"
        git push origin HEAD:${GITHUB_REF#refs/heads/}
