name: SyncLightNovel

on:
  push:
    branches: [ main ]
    paths:
      - '轻小说/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive  
          fetch-depth: 0
          persist-credentials: true

      - name: Install rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "[dropbox]" > ~/.config/rclone/rclone.conf
          echo "type = dropbox" >> ~/.config/rclone/rclone.conf
          echo "token = {\"access_token\":\"${{ secrets.DROPBOX_ACCESS_TOKEN }}\",\"token_type\":\"bearer\",\"expiry\":\"0001-01-01T00:00:00Z\"}" >> ~/.config/rclone/rclone.conf

      - name: 同步到 Dropbox
        run: |
          rclone copy ./ "dropbox:/微凉半度/" \
            --progress \
            --ignore-existing \
            --filter "+ 轻小说/**" \
            --filter "- *"
